### ISSUE TITLE
What do i have to configurate on this timer? 

### ISSUE THREAD

**Issue by T3ED** [Skyline23/bTimes-csgo#5]
What do i have to configurate on this timer? 

"bTimes"
{
"driver"	"mysql"
"host"	"name"
"database"	"name"
"user"	"name"
"pass"	"pass"
//"timeout"	"0"
//"port"	"0"
}

The tables are not created automatic? I have to create them manually?
here is no readme so i rly dont know what to configurate, If u can tell me what to do, please, i rly like that timer but never worked with Something like that before

**Comment by T3ED** [comment]
L 08/07/2017 - 11:04:55: [SM]   [1] Line 973, C:\Users\Utilizator\Desktop\bTimes-csgo-master\bTimes-core.sp::Native_GetNameFromPlayerID
L 08/07/2017 - 11:04:55: [SM]   [3] GetNameFromPlayerID
L 08/07/2017 - 11:04:55: [SM]   [4] Line 519, C:\Users\Utilizator\Desktop\bTimes-csgo-master\bTimes-ghost.sp::GhostCheck
L 08/07/2017 - 11:04:55: [SM] Exception reported: Invalid Handle 0 (error: 4)
L 08/07/2017 - 11:04:55: [SM] Blaming: bTimes-core.smx
L 08/07/2017 - 11:04:55: [SM] Call stack trace:
L 08/07/2017 - 11:04:55: [SM]   [0] GetArrayString
L 08/07/2017 - 11:04:55: [SM]   [1] Line 973, C:\Users\Utilizator\Desktop\bTimes-csgo-master\bTimes-core.sp::Native_GetNameFromPlayerID
L 08/07/2017 - 11:04:55: [SM]   [3] GetNameFromPlayerID
L 08/07/2017 - 11:04:55: [SM]   [4] Line 519, C:\Users\Utilizator\Desktop\bTimes-csgo-master\bTimes-ghost.sp::GhostCheck
L 08/07/2017 - 11:06:27: [SM] Exception reported: Team index 0 is invalid
L 08/07/2017 - 11:06:27: [SM] Blaming: weapons_hades.smx
L 08/07/2017 - 11:06:27: [SM] Call stack trace:
L 08/07/2017 - 11:06:27: [SM]   [0] PTaH_GetItemInLoadout
L 08/07/2017 - 11:06:27: [SM]   [1] Line 56, weapons/hooks.sp::GiveNamedItem
L 08/07/2017 - 11:06:27: [SM]   [3] GivePlayerItem
L 08/07/2017 - 11:06:27: [SM]   [4] Line 34, D:\My Work\SM Plugins\surf_fix.sp::Event_PlayerSpawn
L 08/07/2017 - 11:06:46: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 08/07/2017 - 11:06:46: [SM] Blaming: bTimes-zones.smx
L 08/07/2017 - 11:06:46: [SM] Call stack trace:
L 08/07/2017 - 11:06:46: [SM]   [0] SQL_TQuery
L 08/07/2017 - 11:06:46: [SM]   [1] Line 1334, C:\Users\Utilizator\Desktop\bTimes-csgo-master\bTimes-zones.sp::DB_SaveZone
L 08/07/2017 - 11:06:46: [SM]   [2] Line 829, C:\Users\Utilizator\Desktop\bTimes-csgo-master\bTimes-zones.sp::CreateZone
L 08/07/2017 - 11:06:46: [SM]   [3] Line 759, C:\Users\Utilizator\Desktop\bTimes-csgo-master\bTimes-zones.sp::Menu_AddZone
L 08/07/2017 - 11:07:24: [SM] Exception reported: Team index 0 is invalid

**Comment by Skyline23** [comment]
[https://github.com/Skyline23/bTimes-csgo/blob/master/README.md](sry for being tooooooooooo late)
